pipeline {
    agent any

    environment {
        PATH = "/usr/local/go/bin:$PATH"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/stillfreddie/car-hire-app.git'
            }
        }

        stage('Check Go') {
            steps {
                echo 'Checking Go installation on Jenkins environment...'
                sh 'which go'
                sh 'go version'
            }
        }

        stage('Build') {
            steps {
                echo 'Building Go binary...'
                sh 'go build -o car-hire-app'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t car-hire-app .'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Stopping old container (if any)...'
                sh '''
                docker stop car-hire-app || true
                docker rm car-hire-app || true
                echo "Running new container..."
                docker run -d -p 8080:8080 --name car-hire-app car-hire-app
                '''
            }
        }
    }
}